- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - zsh
        - node
        - fzf
        - rust
        - dotfiles
  tasks:
  - include: ./tasks/ssh.yaml
  - include: ./tasks/git-setup.yaml
  - include: ./tasks/zsh.yaml
  - include: ./tasks/node.yaml
  - include: ./tasks/fzf.yaml
  - include: ./tasks/rust.yaml
  - include: ./tasks/go.yaml
  - include: ./tasks/dotfiles.yaml
