- name: Get zsh path
  command: which zsh
  register: zsh_path
  tags:
    - zsh

- name: Change shell 
  become: true
  user:
    name: "{{ username }}"
    shell: "{{ zsh_path.stdout }}"
  tags:
    - zsh

- name: Install starship
  become: true
  shell: curl -fsSL https://starship.rs/install.sh | sh -s -- -y
  tags:
    - zsh

- name: Check that the somefile.conf exists
  stat:
    path: ~/.oh-my-zsh
  become: no
  register: oh_my_stats
  tags:
    - install
    - productivity
    - zsh

- name: Install Ohmyzsh
  shell: curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh -s -- -y
  become: no
  tags:
    - zsh
  when: oh_my_stats.stat.exists == False

- name: Install the zsh plugin autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  tags:
    - zsh
- name: Install the zsh plugin completions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-completions'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-completions"
  tags:
    - zsh
- name: Install the zsh plugin syntax highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  tags:
    - zsh
