- name: Install stow
  become: true
  package:
    name:
      - stow
    state: present
  tags: "{{ dotfiles_tags }}"

- name: Check if dotfiles repo exists
  stat:
    path: "{{ ansible_facts.user_dir }}/.dotfiles"
  register: dotfiles_stat
  tags: "{{ dotfiles_tags }}"

- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: "https://github.com/merlinvn/dotfiles.git"
    dest: "{{ ansible_facts.user_dir }}/.dotfiles"
    clone: true
    update: true
    force: true
    accept_hostkey: true
  tags: "{{ dotfiles_tags }}"

- name: Use Stow to manage dotfiles
  command: >-
    stow -t {{ ansible_facts.user_dir }}
    -d {{ ansible_facts.user_dir }}/.dotfiles
    --adopt {{ item }}
  loop: "{{ dotfiles_packages | default(['shell', 'vim', 'tmux', 'starship']) }}"
  tags: "{{ dotfiles_tags }}"

- name: Reset dotfiles repo
  command: git reset --hard HEAD
  args:
    chdir: "{{ ansible_facts.user_dir }}/.dotfiles"
  tags: "{{ dotfiles_tags }}"
