- name: Update package cache
  become: true
  apt:
    update_cache: true
  tags:
    - base

- name: Install basic packages
  become: true
  apt:
    name:
      - curl
      - git
      - zsh
      - vim
      - tmux
      - eza
      - ripgrep
      - bat
      - fd-find
      - fortune
      - rsync
      - fzf
      - autojump
      - stow
      - jq
      - build-essential
      - libssl-dev
      - libffi-dev
      - zlib1g-dev
    state: present
  tags:
    - base
