- name: Install curl and dev libraries for Mise
  become: true
  package:
    name:
      - curl
      - libssl-dev
      - libffi-dev
      - zlib1g-dev
    state: present
  tags: "{{ mise_tags }}"

- name: Check if mise is installed
  command: command -v mise
  register: mise_exists
  changed_when: false
  failed_when: false
  tags: "{{ mise_tags }}"

- name: Install Mise
  shell: curl https://mise.jdx.dev/install.sh | sh
  when: mise_exists.rc != 0
  tags: "{{ mise_tags }}"

- name: Add mise activation to .zshrc
  lineinfile:
    path: "{{ ansible_facts.user_dir }}/.zshrc"
    line: 'eval "$(~/.local/bin/mise activate zsh)"'
    create: true
    insertafter: EOF
  tags: "{{ mise_tags }}"
