- name: Check if mise is installed
  command: command -v mise
  register: mise_exists
  changed_when: false
  failed_when: false
  tags: "{{ node_tags }}"

- name: Set global Node.js version to LTS using Mise
  shell: ~/.local/bin/mise use --global node@lts
  when: mise_exists.rc == 0
  tags: "{{ node_tags }}"
