- name: Check if cargo is installed
  command: command -v cargo
  register: cargo_exists
  changed_when: false
  failed_when: false
  tags: "{{ rust_tags }}"

- name: Install Rust
  shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
  when: cargo_exists.rc != 0
  tags: "{{ rust_tags }}"
