- hosts: new_pc
  vars:
    username: "{{ ansible_user }}"
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ ansible_env.HOME }}/.ssh/id_rsa"
    home_path: "{{ ansible_env.HOME }}"
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        update_cache: true
      tags:
        - zsh
        - node
        - fzf
        - dotfiles
        - other-tools
  tasks:
    - include_tasks: ./tasks/basic-packages.yaml
    - include_tasks: ./tasks/ssh.yaml
    - include_tasks: ./tasks/git-setup.yaml
    - include_tasks: ./tasks/zsh.yaml
    - include_tasks: ./tasks/node.yaml
    - include_tasks: ./tasks/fzf.yaml
    - include_tasks: ./tasks/rust.yaml
    - include_tasks: ./tasks/go.yaml
    - include_tasks: ./tasks/dotfiles.yaml
