---
- name: Install containerd
  ansible.builtin.apt:
    name: containerd
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: containerd_enabled

- name: Enable containerd
  ansible.builtin.systemd:
    name: containerd
    enabled: true
    state: started
  when: containerd_enabled
